version: "3.7"

services:
  master:
    image: ${DOCKER_TAG}
    container_name: master
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - 'es-network'
    volumes:
      - /Users/${USER}/.aws/credentials:/Users/root/.aws/credentials/

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - 'es-network'
    volumes:
      - db:/var/lib/postgresql/data
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../scripts/data.sql:/home/data.sql
      - /Users/${USER}/Desktop/Decover/DBDumps:/home/

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - node.name=es01
      - cluster.name=es-cluster-1
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

volumes:
  db:
    driver: local
  master:
    driver: local

networks:
  es-network:
    driver: bridge
