version: "3.0"

services:
  master:
    image: ravitandon2/master-300-prod:0.3
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: decover-logs
        awslogs-region: us-east-1
        awslogs-stream-prefix: master-300
    links:
      - db
      - es01
    networks:
      - 'es-network'
    volumes:
      - master-data:/root/.aws
      - /Users/ravi/.aws/credentials:/Users/root/.aws/
      
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster-1
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
      - 'es-network'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

volumes:
  db-data:
  master-data:
